# Generated by Django 4.2 on 2023-04-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='Blank', max_length=8),
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='Blank', max_length=1000),
        ),
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.IntegerField(default=2),
        ),
    ]
