# Generated by Django 4.2 on 2023-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_course_course_code_course_course_title_course_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Required', 'Required'), ('Elective', 'Elective')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='unit',
            field=models.IntegerField(null=True),
        ),
    ]
